language: objective-c
osx_image: xcode8

## Setup

# Travis initializes git submodules before `install` runs

install:
    # - `xctool`, required to build the unit test and documentation targets
    #   Workaround for https://github.com/travis-ci/travis-ci/issues/2051#issuecomment-40817341
    - brew update
    - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:
    - xcodebuild -target TBLCategories
    - xcodebuild -target TBLCategories -scheme TBLCategories -destination 'platform=iOS Simulator,name=iPhone 6' test
